# This is a basic workflow that is manually triggered

name: Modules deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push: # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master
    # Sequence of patterns matched against refs/tags

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_servers:
    name: Deploy modules
    runs-on: server-main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy source
      run: |
        source=`pwd`
        cd $SERVER_CONFIGS_PATH
        source ./env.sh
        mkdir -p ./data/stddom_new
        echo "let date="\"$(date -u +"%d%m%Y_%H%M%S")\""; export {date};">./data/stddom_new/version.js
        cp -rf -t ./data/stddom_new/ $source/*
        mv -fT ./data/stddom ./data/stddom_old
        mv -fT ./data/stddom_new ./data/stddom
        rm -rf ./data/stddom_old
    - name: Update modules
      run: |
        bash ./.github/workflows/update_modules.sh

